import type { Turf, Review } from "./types";

// Turf venues are based on real, publicly-listed grounds around
// Nalasopara / Vasai-Virar, Palghar, Maharashtra. Slot inventory,
// prices and ratings are illustrative demo values.
export const TURFS: Turf[] = [
  {
    id: "camp-nou", name: "Camp Nou Arena", kind: "Rooftop football & box cricket",
    sports: ["football", "cricket"], primary: "football",
    area: "Vasant Nagari, Nalasopara East", pin: "401209", distLabel: "1.1 km",
    lat: 19.4275, lng: 72.8262, rating: 4.7, reviews: 184, price: 1100,
    surface: "Bellin 50mm 4G", formats: ["5v5", "7v7", "9v9", "Box cricket"], open24: true,
    openLabel: "Open 24 hours", openH: 0, closeH: 24, fieldCount: 2, unit: "Pitch",
    blurb: "Floodlit rooftop arena with imported 4G grass and full nets. The neighbourhood favourite for late-night five-a-side and weekend box-cricket leagues.",
    amenities: ["4G turf", "Floodlights", "Washrooms", "Drinking water", "Seating area", "Bibs & balls", "Parking"],
    spotsLeft: 6, popular: true,
  },
  {
    id: "box-park", name: "The Box Park Turf", kind: "FIFA-grade football turf",
    sports: ["football", "cricket"], primary: "football",
    area: "Vasai East", pin: "401208", distLabel: "3.6 km",
    lat: 19.3905, lng: 72.8330, rating: 4.8, reviews: 312, price: 1300,
    surface: "Vietnam Bellin 50mm · FIFA approved", formats: ["7v7", "9v9", "11v11"], open24: false,
    openLabel: "6:00 AM – 1:00 AM", openH: 6, closeH: 25, fieldCount: 2, unit: "Pitch",
    blurb: "The area’s first FIFA-approved pitch, laid with imported Bellin 50mm turf. Premium grip, true bounce and a proper match-day feel under stadium lights.",
    amenities: ["FIFA turf", "Floodlights", "Changing rooms", "Cafeteria", "First aid", "Parking", "Live scoring"],
    spotsLeft: 3, popular: true,
  },
  {
    id: "dream-arena", name: "Dream Arena Turf", kind: "Football & volleyball",
    sports: ["football", "cricket"], primary: "football",
    area: "Stella, Vasai West", pin: "401202", distLabel: "5.2 km",
    lat: 19.3618, lng: 72.8090, rating: 4.6, reviews: 142, price: 1000,
    surface: "40mm synthetic turf", formats: ["5v5", "7v7", "9v9", "Box cricket"], open24: false,
    openLabel: "5:30 AM – 12:00 AM", openH: 6, closeH: 24, fieldCount: 2, unit: "Pitch",
    blurb: "Spacious turf behind Stella petrol pump with a relaxed crowd, great for friendly fixtures and corporate games. Easy parking and quick booking.",
    amenities: ["Synthetic turf", "Floodlights", "Washrooms", "Drinking water", "Parking", "Seating area"],
    spotsLeft: 8, popular: true,
  },
  {
    id: "sandor", name: "Sandor Sports", kind: "Multi-sport cricket & football",
    sports: ["cricket", "football"], primary: "cricket",
    area: "Vasai West", pin: "401202", distLabel: "5.8 km",
    lat: 19.3585, lng: 72.8025, rating: 4.5, reviews: 96, price: 900,
    surface: "Astro cricket matting", formats: ["Box cricket", "6v6"], open24: false,
    openLabel: "6:00 AM – 11:30 PM", openH: 6, closeH: 23, fieldCount: 3, unit: "Pitch",
    blurb: "Dedicated box-cricket nets with side football turf, certified coaching and a steady stream of weekend tournaments. Bring the squad or join a league.",
    amenities: ["Cricket nets", "Coaching", "Floodlights", "Washrooms", "Equipment rental", "Parking"],
    spotsLeft: 4, popular: false,
  },
  {
    id: "achievers", name: "Achievers Turf", kind: "5-a-side football",
    sports: ["football"], primary: "football",
    area: "Nalasopara West", pin: "401203", distLabel: "2.4 km",
    lat: 19.4150, lng: 72.8050, rating: 4.4, reviews: 78, price: 850,
    surface: "40mm turf", formats: ["5v5", "6v6"], open24: false,
    openLabel: "6:00 AM – 12:00 AM", openH: 6, closeH: 24, fieldCount: 1, unit: "Pitch",
    blurb: "Compact, well-kept neighbourhood pitch perfect for quick five-a-side after work. Honest pricing and a friendly regulars’ community.",
    amenities: ["Synthetic turf", "Floodlights", "Drinking water", "Washrooms", "Parking"],
    spotsLeft: 5, popular: false,
  },
  {
    id: "smash-pickle", name: "Smash Pickleball Club", kind: "Acrylic pickleball courts",
    sports: ["pickleball"], primary: "pickleball",
    area: "Nalasopara East", pin: "401209", distLabel: "1.8 km",
    lat: 19.4225, lng: 72.8340, rating: 4.9, reviews: 64, price: 600,
    surface: "Acrylic hard court", formats: ["Singles", "Doubles"], open24: false,
    openLabel: "6:00 AM – 10:30 PM", openH: 6, closeH: 22, fieldCount: 4, unit: "Court",
    blurb: "The area’s buzziest pickleball spot — four pro acrylic courts, paddles on rent and a welcoming community of regulars. Great for beginners and dinking pros.",
    amenities: ["Acrylic courts", "Paddle rental", "Floodlights", "Coaching", "Cafe", "Parking"],
    spotsLeft: 4, popular: true,
  },
  {
    id: "shuttle-hub", name: "ShuttleHub Indoor", kind: "6 synthetic badminton courts",
    sports: ["badminton"], primary: "badminton",
    area: "Nalasopara West", pin: "401203", distLabel: "3.0 km",
    lat: 19.4080, lng: 72.7995, rating: 4.6, reviews: 158, price: 450,
    surface: "BWF synthetic mat", formats: ["Singles", "Doubles"], open24: false,
    openLabel: "5:30 AM – 11:30 PM", openH: 6, closeH: 23, fieldCount: 6, unit: "Court",
    blurb: "Six BWF-spec synthetic mat courts under one roof with anti-glare lighting and a coaching academy. Book a single court or the whole hall for league night.",
    amenities: ["Synthetic mats", "Academy", "Air-cooled", "Racket rental", "Cafeteria", "Parking"],
    spotsLeft: 6, popular: false,
  },
  {
    id: "ace-tennis", name: "Ace Tennis Centre", kind: "Hard-court tennis",
    sports: ["tennis"], primary: "tennis",
    area: "Virar West", pin: "401303", distLabel: "7.4 km",
    lat: 19.4530, lng: 72.7920, rating: 4.5, reviews: 52, price: 700,
    surface: "Synthetic hard court", formats: ["Singles", "Doubles"], open24: false,
    openLabel: "6:00 AM – 10:00 PM", openH: 6, closeH: 22, fieldCount: 2, unit: "Court",
    blurb: "Two pro hard courts with coaching on request, smooth bounce and fresh line markings. Ball-machine rental available for solo practice.",
    amenities: ["Hard court", "Coaching", "Ball machine", "Lockers", "Pro shop", "Parking"],
    spotsLeft: 2, popular: false,
  },
];

export const REVIEWS: Review[] = [
  { who: "Rohan S.", initials: "RS", rating: 5, whenLbl: "2 weeks ago", text: "Best turf in Nalasopara. Lights are bright, grass is fresh and booking took 30 seconds. Squad loved it." },
  { who: "Aisha K.", initials: "AK", rating: 4, whenLbl: "1 month ago", text: "Great pitch and easy to split the bill with friends. Parking gets tight on weekends — go early." },
  { who: "Manish J.", initials: "MJ", rating: 5, whenLbl: "1 month ago", text: "We run our Sunday league here. Nets are proper and the staff are helpful. Highly recommend." },
];

export const DEMO_USER = {
  name: "Aarav",
  fullName: "Aarav Sharma",
  email: "aarav@turfie.in",
  phone: "+91 98200 12345",
  initials: "AS",
  city: "Nalasopara",
  level: "Intermediate",
  password: "turfie123",
};
